apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpetstore-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jpetstore
  template:
    metadata:
      labels:
        app: jpetstore
    spec:
      containers:
      - name: jpetstore
        image: rohitsonawane7725/car_price_image:pet_v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: jpetstore-ssvc
spec:
  selector:
    app: jpetstore
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080

